// pages/works/nearstation.tsx
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useRef } from 'react';
import styled from 'styled-components';
import NearStationPic from '../../assets/works/nearstation.png';
import Button from '../../components/Button';
import MySQLIcon from '../../components/marks/MySQLIcon';
import NestJSIcon from '../../components/marks/NestJSIcon';
import ReactIcon from '../../components/marks/ReactIcon';
import TSIcon from '../../components/marks/TSIcon';
import Postit from '../../components/Postit';
import SkillsCircle from '../../components/SkillsCircle';
import TitlePostit from '../../components/TitlePostit';
import {
  imageAnimation,
  singleHeadingPostitAnimation,
  titlePostitAnimation,
} from '../../constants/keyframets';
import useScreenVisibility from '../../hooks/useScreenVisibility';

const Container = styled.section<{ fullHeight?: boolean }>`
  position: relative;
  min-height: calc(100vh - 48px);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  background: ${({ theme }) => theme.bg};
  &:nth-child(even) {
    background: ${({ theme }) => theme.subBg};
  }
  &:first-child {
    min-height: 100vh;
  }

  min-height: ${({ fullHeight }) => (fullHeight ? '100vh' : undefined)};
`;

const ContentContainer = styled.article`
  width: 100%;
  min-height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  margin-top: 144px;
  padding-bottom: 32px;
  &:first-child {
    margin-top: 48px;
  }

  @media (min-width: 800px) {
    padding-bottom: 64px;
  }
`;

const Anchor = styled.a`
  margin-bottom: 32px;
`;

const StyledPostit = styled(Postit)`
  display: block;
  margin-bottom: 32px;
  animation: ${singleHeadingPostitAnimation} 1s ease forwards;
`;

const Name = styled.h2`
  margin-top: 32px;
  font-size: 2rem;
  text-align: center;
  font-weight: bold;
  color: ${({ theme }) => theme.text};
`;

const LogoContainer = styled.div`
  opacity: 0;
  width: 210px;
  height: auto;
  filter: drop-shadow(0 3px 6px rgba(0, 0, 0, 0.16));
  animation: ${imageAnimation} 1s ease 0.25s forwards;
`;

const Bio = styled.p`
  text-align: center;
  max-width: calc(100% - 64px);
  line-height: 1.75;
  margin-top: 12px;
  color: ${({ theme }) => theme.text};
`;

const Concept = styled.h2`
  text-align: center;
  line-height: 1.5;
  font-size: 2rem;
  color: ${({ theme }) => theme.text};
  font-weight: bold;
  max-width: 90%;
`;
const ConceptDescription = styled.p`
  text-align: left;
  max-width: 90%;
  margin-top: 32px;
  line-height: 2;
  color: ${({ theme }) => theme.text};
  @media (min-width: 800px) {
    text-align: center;
  }
`;

const TechContainer = styled.article`
  margin-top: 64px;
  width: 75%;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  grid-gap: 32px;
  animation: ${imageAnimation} 1s ease forwards;
`;

const StyledTitlePostit = styled(TitlePostit)`
  animation: ${titlePostitAnimation} 1s ease forwards;
`;
const FirstSection: React.FC = () => (
  <Container fullHeight>
    <ContentContainer>
      <StyledPostit>Dev/WebApp</StyledPostit>
      <LogoContainer>
        <Image src={NearStationPic} alt="NearStation" />
      </LogoContainer>
      <Name>NearStation</Name>
      <Bio>最寄り駅とその路線がひと目で分かるWebアプリ</Bio>
    </ContentContainer>
  </Container>
);

const ConceptSection: React.FC = () => {
  const ref = useRef(null);
  const visible = useScreenVisibility(ref);

  return (
    <Container ref={ref}>
      {visible && <TitlePostit title="NearStation" subtitle="コンセプト" />}
      <ContentContainer>
        <Concept>今いる場所の最寄り駅と路線を知りたい</Concept>
        <ConceptDescription>
          StationAPIの応用例の一つです。
          <br />
          シンプルに今いる場所の最寄り駅の名前と
          <br />
          駅の路線の停車駅を知りたいときに役に立つと思い、開発しました。
          <br />
          今いる駅の路線がどこに行くのか知りたいときなどにお役に立つかと思います。
        </ConceptDescription>
      </ContentContainer>
    </Container>
  );
};

const TechnologySection: React.FC = () => {
  const ref = useRef(null);
  const visible = useScreenVisibility(ref);

  return (
    <Container ref={ref}>
      {visible && <StyledTitlePostit title="NearStation" subtitle="使用技術" />}
      {visible && (
        <TechContainer>
          <SkillsCircle icon={TSIcon} name="TypeScript" />
          <SkillsCircle icon={ReactIcon} name="React.js" />
          <SkillsCircle icon={NestJSIcon} name="NestJS" />
          <SkillsCircle icon={MySQLIcon} name="MySQL" />
        </TechContainer>
      )}
    </Container>
  );
};

const AccessSection: React.FC = () => {
  const ref = useRef(null);
  const visible = useScreenVisibility(ref);

  return (
    <Container ref={ref}>
      {visible && <StyledTitlePostit title="NearStation" subtitle="リンク" />}
      <ContentContainer>
        <Anchor
          href="https://near.tinykitten.me"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Button>使ってみる</Button>
        </Anchor>
        <Anchor
          href="https://github.com/TinyKitten/NearStation"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Button>リポジトリ</Button>
        </Anchor>
        <Anchor>
          <Link href="/" passHref>
            <div>
              <Button color="#555">戻る</Button>
            </div>
          </Link>
        </Anchor>
      </ContentContainer>
    </Container>
  );
};

const WorksNearStationPage: React.FC = () => {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    ref.current?.scrollIntoView();
  }, []);

  return (
    <div ref={ref}>
      <Head>
        <title>NearStation</title>
        <meta
          name="description"
          content="最寄り駅とその路線がひと目で分かるWebアプリ"
        />
        <meta property="og:site_name" content="TinyKitten" />
        <meta property="og:type" content="article" />
        <meta
          property="og:url"
          content={`${process.env.PUBLIC_URL}/works/nearstation`}
        />
        <meta property="og:title" content="NearStation" />
        <meta
          property="og:description"
          content="最寄り駅とその路線がひと目で分かるWebアプリ"
        />
        <meta property="og:image" content="/works/nearstation.png" />
      </Head>
      <FirstSection />
      <ConceptSection />
      <TechnologySection />
      <AccessSection />
    </div>
  );
};

export function getStaticProps(): {
  props: unknown;
  revalidate: number;
} {
  return {
    props: {},
    revalidate: 60,
  };
}

export default WorksNearStationPage;

// pages/works/nearstation.vue
<template>
  <div>
    <section class="container">
      <article class="content">
        <app-postit class="postit" text="Dev/WebApp" />
        <img
          class="logo"
          src="~/assets/works/nearstation.png"
          alt="NearStation"
        >
        <h2 class="name">
          NearStation
        </h2>
        <p class="bio">
          最寄り駅とその路線がひと目で分かるWebアプリ
        </p>
      </article>
    </section>
    <section class="container">
      <app-title-postit
        v-if="visible"
        title="NearStation"
        subtitle="コンセプト"
      />
      <article class="content">
        <h2 class="concept">
          今いる場所の最寄り駅と路線を知りたい
        </h2>
        <p class="conceptDescription">
          <a
            href="https://github.com/TinyKitten/StationAPI"
            target="_blank"
            rel="noopener noreferrer"
          >StationAPI</a>の応用例の一つです。<br>
          シンプルに今いる場所の最寄り駅の名前と<br>
          駅の路線の停車駅を知りたいときに役に立つと思い、開発しました。<br>
          今いる駅の路線がどこに行くのか知りたいときなどにお役に立つかと思います。
        </p>
      </article>
    </section>
    <section class="container">
      <app-title-postit
        v-if="visible"
        title="NearStartion"
        subtitle="デザイン"
      />
      <article class="content">
        <img
          class="galleryImg"
          src="~/assets/works/nearstation.png"
          alt="NearStation"
        >
        <h2 class="galleryConcept">
          すっきりと透き通るような繊細なデザイン
        </h2>
      </article>
    </section>
    <section class="container">
      <app-title-postit
        v-if="visible"
        title="NearStation"
        subtitle="使用技術"
      />
      <article class="techs">
        <app-skill-circle
          :image-path="require('~/assets/marks/ts.svg')"
          skill-name="TypeScript"
        />
        <app-skill-circle
          :image-path="require('~/assets/marks/react.svg')"
          skill-name="React.js"
        />
        <app-skill-circle
          :image-path="require('~/assets/marks/nestjs.svg')"
          skill-name="NestJS"
        />
        <app-skill-circle
          :image-path="require('~/assets/marks/mysql.svg')"
          skill-name="MySQL"
        />
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="NearStation" subtitle="リンク" />
      <article class="content">
        <a
          href="https://near.tinykitten.me"
          target="_blank"
          class="link"
          rel="noopener noreferrer"
        >
          <app-button text="使ってみる" />
        </a>
        <a
          href="https://github.com/TinyKitten/NearStation"
          target="_blank"
          class="link"
          rel="noopener noreferrer"
        >
          <app-button text="リポジトリ" />
        </a>
        <nuxt-link to="/" class="link">
          <app-button color="#555" text="戻る" />
        </nuxt-link>
      </article>
    </section>
  </div>
</template>

<script>
import AppTitlePostit from '~/components/AppTitlePostit.vue'
import AppPostit from '~/components/AppPostit.vue'
import AppButton from '~/components/AppButton.vue'
import AppSkillCircle from '~/components/AppSkillCircle.vue'
import { scrollMixin } from '~/mixins/scroll'

export default {
  components: {
    AppPostit,
    AppTitlePostit,
    AppButton,
    AppSkillCircle
  },
  mixins: [scrollMixin],
  head: {
    title: 'NearStation',
    description: '最寄り駅とその路線がひと目で分かるWebアプリ',
    meta: [
      { hid: 'og:site_name', property: 'og:site_name', content: 'TinyKitten' },
      { hid: 'og:type', property: 'og:type', content: 'article' },
      {
        hid: 'og:url',
        property: 'og:url',
        content: 'https://tinykitten.me/works/nearstation/'
      },
      {
        hid: 'og:title',
        property: 'og:title',
        content: 'NearStation'
      },
      {
        hid: 'og:description',
        property: 'og:description',
        content: '最寄り駅とその路線がひと目で分かるWebアプリ'
      },
      {
        hid: 'og:image',
        property: 'og:image',
        content: `https://tinykitten.me${require('~/assets/works/nearstation.png')}`
      }
    ]
  }
}
</script>

<style scoped>
.container {
  position: relative;
  min-height: calc(100vh - 48px);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}

.container:first-child {
  min-height: 100vh;
}

.content {
  width: 100%;
  min-height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  margin-top: 144px;
  padding-bottom: 32px;
}

.content:first-child {
  margin-top: 48px;
}

.container:nth-child(even) {
  background: #fafafa;
}

.logo {
  opacity: 0;
  width: auto;
  max-height: 320px;
  height: auto;
  filter: drop-shadow(0 3px 6px rgba(0, 0, 0, 0.16));
  animation: imageAnimation 1s ease 0.25s forwards;
}

.bio {
  text-align: center;
  max-width: calc(100% - 64px);
  line-height: 1.75;
  margin-top: 12px;
  color: #555;
}

.name {
  margin-top: 32px;
  font-size: 2rem;
  text-align: center;
  font-weight: bold;
  color: #707070;
}

.postit {
  display: block;
  margin-bottom: 32px;
  animation: headingPostitAnimation 1s ease forwards;
}

.titlePostit {
  animation: titlePostitAnimation 1s ease forwards;
}

.concept {
  text-align: center;
  line-height: 1.5;
  font-size: 2rem;
  color: #555555;
  font-weight: bold;
  max-width: 90%;
}

.galleryConcept {
  text-align: center;
  line-height: 1.5;
  font-size: 1.5rem;
  color: #555555;
  font-weight: bold;
  max-width: 90%;
}

.conceptDescription {
  text-align: center;
  max-width: 90%;
  margin-top: 32px;
  line-height: 2;
  color: #555;
}

.conceptDescription a {
  color: #555;
  font-weight: bold;
  text-decoration: none;
}

.galleryImg {
  margin: 64px 0 32px 0;
  width: 320px;
  height: auto;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16);
}

.link {
  margin-bottom: 32px;
}

.appStoreButton {
  width: 210px;
  height: auto;
  overflow: hidden;
  margin-bottom: 12px;
}

.appStoreButton img {
  width: 100%;
  height: auto;
}

.appleAppStore {
  width: 180px;
  margin-bottom: 32px;
}

.smallCaption {
  font-size: 0.8rem;
  margin-top: 0;
}

.techs {
  margin-top: 64px;
  width: 75%;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  grid-gap: 32px;
  animation: imageAnimation 1s ease forwards;
}

/* Animation */
@keyframes titlePostitAnimation {
  from {
    transform: translateY(-147px);
  }
  to {
    transform: translateY(0);
  }
}

@keyframes headingPostitAnimation {
  from {
    opacity: 0;
    transform: translateY(-64px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes imageAnimation {
  from {
    opacity: 0;
    transform: translateY(-32px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (min-width: 800px) {
  .content {
    padding-bottom: 64px;
  }
}
</style>
