// app/works/trainlcd/page.tsx
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useRef } from 'react';
import styled from 'styled-components';
import Button from '../../../components/Button';
import Postit from '../../../components/Postit';
import SkillsCircle from '../../../components/SkillsCircle';
import StyledImage from '../../../components/StyledImage';
import TitlePostit from '../../../components/TitlePostit';
import Tree from '../../../components/Tree';
import MySQLIcon from '../../../components/marks/MySQLIcon';
import ReactIcon from '../../../components/marks/ReactIcon';
import RustIcon from '../../../components/marks/RustIcon';
import TSIcon from '../../../components/marks/TSIcon';
import TonicIcon from '../../../components/marks/TonicIcon';
import {
  imageAnimation,
  singleHeadingPostitAnimation,
} from '../../../constants/keyframets';
import storiesArray from '../../../fixtures/stories/works/trainlcd.stories.json';
import useScreenVisibility from '../../../hooks/useScreenVisibility';
import TrainLCDImage from '../../assets/works/trainlcd.png';

const Container = styled.section<{ padTop?: boolean }>`
  position: relative;
  min-height: 100vh;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  background: ${({ theme }) => theme.bg};
  &:nth-child(even) {
    background: ${({ theme }) => theme.subBg};
  }
  &:first-child {
    min-height: 100vh;
    margin-top: -48px;
  }
  padding-top: ${({ padTop }) => (padTop ? '144px' : '0px')};
`;

const ContentContainer = styled.article`
  width: 100%;
  min-height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  margin-top: 144px;
  @media (min-width: 800px) {
    margin-top: 0;
  }
`;

const Anchor = styled.a`
  margin-bottom: 32px;
`;

const StyledPostit = styled(Postit)`
  display: block;
  margin-bottom: 32px;
  animation: ${singleHeadingPostitAnimation} 1s ease forwards;
`;

const Name = styled.h2`
  margin-top: 32px;
  font-size: 2rem;
  text-align: center;
  font-weight: bold;
  color: ${({ theme }) => theme.text};
`;

const LogoContainer = styled.div`
  position: relative;
  opacity: 0;
  width: 320px;
  height: auto;
  filter: drop-shadow(0 3px 6px rgba(0, 0, 0, 0.16));
  animation: ${imageAnimation} 1s ease 0.25s forwards;
  @media (min-width: 800px) {
    width: 480px;
  }
`;

const Bio = styled.p`
  text-align: center;
  max-width: calc(100% - 64px);
  line-height: 1.75;
  margin-top: 12px;
  color: ${({ theme }) => theme.text};
`;

const Concept = styled.h2`
  line-height: 1.5;
  font-size: 2rem;
  color: ${({ theme }) => theme.text};
  font-weight: bold;
  max-width: 90%;
`;
const ConceptDescription = styled.p`
  text-align: left;
  max-width: 90%;
  margin-top: 16px;
  line-height: 2;
  color: ${({ theme }) => theme.text};
  @media (min-width: 800px) {
    text-align: center;
  }
`;
const ConceptDescriptionAnchor = styled.a`
  color: ${({ theme }) => theme.text};
  font-weight: bold;
  text-decoration: none;
`;

const SmallCaption = styled.small`
  text-align: left;
  max-width: 90%;
  margin-top: 32px;
  line-height: 2;
  color: ${({ theme }) => theme.text};
  font-size: 0.8rem;
  margin-top: 0;
  width: 100%;
  @media (min-width: 800px) {
    text-align: center;
  }
`;

const TechContainer = styled.article`
  margin-top: 64px;
  width: 75%;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  grid-gap: 32px;
  animation: ${imageAnimation} 1s ease forwards;
`;

const TreeContainer = styled.article`
  margin: 64px 0;
`;

const FirstSection: React.FC = () => (
  <Container>
    <StyledPostit>Dev/MobileApp</StyledPostit>
    <LogoContainer>
      <StyledImage fill sizes="320px" src={TrainLCDImage} alt="TrainLCD" />
    </LogoContainer>
    <Name>TrainLCD</Name>
    <Bio>日本全国の鉄道路線で使える新感覚のナビゲーションアプリ</Bio>
  </Container>
);

const ConceptSection: React.FC = () => {
  const ref = useRef(null);
  const visible = useScreenVisibility(ref);

  return (
    <Container ref={ref}>
      {visible && <TitlePostit title="TrainLCD" subtitle="コンセプト" />}
      <ContentContainer>
        <Concept>Webの技術で電車のLCDを再現したい</Concept>
        <ConceptDescription>
          このアプリの開発を始める前に趣味で作っていた
          <ConceptDescriptionAnchor
            href="https://github.com/TinyKitten/StationAPI"
            target="_blank"
            rel="noopener noreferrer"
          >
            StationAPI
          </ConceptDescriptionAnchor>
          の応用例の一つです。 <br />
          以前より電車のLCDを再現したいと思っていて、
          <ConceptDescriptionAnchor
            href="https://github.com/TinyKitten/StationAPI"
            target="_blank"
            rel="noopener noreferrer"
          >
            StationAPI
          </ConceptDescriptionAnchor>
          の大型アップデートで色々取れるようにした影響で作ろうと思いました。
          <br />
          満員電車、LCDのない路線など、現在どこにいるか、どの駅を通るのかひと目で分かります。
          <br />
          ぜひお試しください。
        </ConceptDescription>
        <SmallCaption>※地下区間は非対応です</SmallCaption>
      </ContentContainer>
    </Container>
  );
};

const TechnologySection: React.FC = () => {
  const ref = useRef(null);
  const visible = useScreenVisibility(ref);

  return (
    <Container padTop ref={ref}>
      {visible && <TitlePostit title="TrainLCD" subtitle="使用技術" />}
      {visible && (
        <TechContainer>
          <SkillsCircle icon={TSIcon} name="TypeScript" />
          <SkillsCircle icon={ReactIcon} name="React Native" />
          <SkillsCircle icon={RustIcon} name="Rust" />
          <SkillsCircle icon={TonicIcon} name="Tonic" />
          <SkillsCircle icon={MySQLIcon} name="MySQL" />
        </TechContainer>
      )}
    </Container>
  );
};

const StoriesSection: React.FC = () => {
  const ref = useRef(null);
  const visible = useScreenVisibility(ref);

  return (
    <Container padTop ref={ref}>
      {visible && <TitlePostit title="TrainLCD" subtitle="ストーリー" />}
      {visible && (
        <TreeContainer>
          <Tree
            experienceType="worksStory"
            items={storiesArray}
            visible
            worksName="trainlcd"
          />
        </TreeContainer>
      )}
    </Container>
  );
};

const AccessSection: React.FC = () => {
  const ref = useRef(null);
  const visible = useScreenVisibility(ref);

  return (
    <Container ref={ref}>
      {visible && <TitlePostit title="TrainLCD" subtitle="リンク" />}
      <ContentContainer>
        <Anchor
          href="https://trainlcd.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Button>公式サイト</Button>
        </Anchor>
        <Anchor
          href="https://github.com/TrainLCD/MobileApp"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Button>リポジトリ</Button>
        </Anchor>

        <Link href="/" passHref>
          <div>
            <Button color="#555">戻る</Button>
          </div>
        </Link>
      </ContentContainer>
    </Container>
  );
};

const WorksTrainLCDPage = () => {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    ref.current?.scrollIntoView();
  }, []);

  return (
    <div ref={ref}>
      <Head>
        <title>TrainLCD</title>
        <meta
          name="description"
          content="日本全国の鉄道路線で使える新感覚のナビゲーションアプリ"
        />
        <meta property="og:site_name" content="TinyKitten" />
        <meta property="og:type" content="article" />
        <meta
          property="og:url"
          content={`${process.env.PUBLIC_URL}/works/trainlcd`}
        />
        <meta property="og:title" content="TrainLCD" />
        <meta
          property="og:description"
          content="日本全国の鉄道路線で使える新感覚のナビゲーションアプリ"
        />
        <meta property="og:image" content="/works/trainlcd.png" />
      </Head>
      <FirstSection />
      <ConceptSection />
      <StoriesSection />
      <TechnologySection />
      <AccessSection />
    </div>
  );
};

export default WorksTrainLCDPage;

// pages/works/trainlcd.vue
<template>
  <div>
    <section class="container">
      <article class="content">
        <app-postit class="postit" text="Dev/WebApp" />
        <img class="logo" src="~/assets/works/trainlcd.png" alt="TrainLCD">
        <h2 class="name">
          TrainLCD
        </h2>
        <p class="bio">
          電車のLCDをスマホで
        </p>
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="TrainLCD" subtitle="コンセプト" />
      <article class="content">
        <h2 class="concept">
          StationAPIで電車のLCDを再現したい
        </h2>
        <p class="conceptDescription">
          <a
            href="https://github.com/TinyKitten/StationAPI"
            target="_blank"
            rel="noopener noreferrer"
          >StationAPI</a>の応用例の一つです。 <br>前から電車のLCDを再現したいと思っていて、
          <a
            href="https://github.com/TinyKitten/StationAPI"
            target="_blank"
            rel="noopener noreferrer"
          >StationAPI</a>の大型アップデートで色々取れるようにした影響で作ろうと思いました。<br>
          満員電車、LCDのない路線など、現在どこにいるか、どの駅を通るのかひと目で分かります。<br>
          ぜひお試しください。
        </p>
        <small
          class="conceptDescription smallCaption"
        >※地下区間は非対応です</small>
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="TrainLCD" subtitle="デザイン" />
      <article class="content">
        <img
          class="galleryImg"
          src="~/assets/works/trainlcd.png"
          alt="TrainLCD"
        >
        <h2 class="galleryConcept">
          実物のLCDに近づくように
        </h2>
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="TrainLCD" subtitle="使用技術" />
      <article class="techs">
        <app-skill-circle
          :image-path="require('~/assets/marks/ts.svg')"
          skill-name="TypeScript"
        />
        <app-skill-circle
          :image-path="require('~/assets/marks/react.svg')"
          skill-name="React Native"
        />
        <app-skill-circle
          :image-path="require('~/assets/marks/nestjs.svg')"
          skill-name="NestJS"
        />
        <app-skill-circle
          :image-path="require('~/assets/marks/mysql.svg')"
          skill-name="MySQL"
        />
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="TrainLCD" subtitle="リンク" />
      <article class="content">
        <a
          class="appStoreButton"
          href="https://play.google.com/store/apps/details?id=me.tinykitten.trainlcd&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1"
        >
          <img
            alt="Google Play で手に入れよう"
            src="~/assets/works/store-badges/google-play-store.svg"
          >
        </a>
        <a
          class="appStoreButton appleAppStore"
          href="https://apps.apple.com/jp/app/trainlcd/id1486355943"
        >
          <img
            alt="App Storeからダウンロード"
            src="~/assets/works/store-badges/apple-app-store.svg"
          >
        </a>
        <a
          href="https://github.com/TinyKitten/TrainLCD"
          target="_blank"
          class="link"
          rel="noopener noreferrer"
        >
          <app-button text="リポジトリ" />
        </a>
        <nuxt-link to="/" class="link">
          <app-button color="#555" text="戻る" />
        </nuxt-link>
      </article>
    </section>
  </div>
</template>

<script>
import AppTitlePostit from '~/components/AppTitlePostit.vue'
import AppPostit from '~/components/AppPostit.vue'
import AppButton from '~/components/AppButton.vue'
import AppSkillCircle from '~/components/AppSkillCircle.vue'
import { scrollMixin } from '~/mixins/scroll'

export default {
  components: {
    AppPostit,
    AppTitlePostit,
    AppButton,
    AppSkillCircle
  },
  mixins: [scrollMixin],
  head: {
    title: 'TrainLCD',
    description: '電車のLCDをスマホで',
    meta: [
      { hid: 'og:site_name', property: 'og:site_name', content: 'TinyKitten' },
      { hid: 'og:type', property: 'og:type', content: 'article' },
      {
        hid: 'og:url',
        property: 'og:url',
        content: 'https://tinykitten.me/works/trainlcd/'
      },
      {
        hid: 'og:title',
        property: 'og:title',
        content: 'TrainLCD'
      },
      {
        hid: 'og:description',
        property: 'og:description',
        content: '電車のLCDをスマホで'
      },
      {
        hid: 'og:image',
        property: 'og:image',
        content: `https://tinykitten.me${require('~/assets/works/trainlcd.png')}`
      }
    ]
  }
}
</script>

<style scoped>
.container {
  position: relative;
  min-height: calc(100vh - 48px);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}

.container:first-child {
  min-height: 100vh;
}

.content {
  width: 100%;
  min-height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  margin-top: 144px;
  padding-bottom: 32px;
}

.content:first-child {
  margin-top: 48px;
}

.container:nth-child(even) {
  background: #fafafa;
}

.logo {
  opacity: 0;
  width: 320px;
  height: auto;
  filter: drop-shadow(0 3px 6px rgba(0, 0, 0, 0.16));
  animation: imageAnimation 1s ease 0.25s forwards;
}

.bio {
  text-align: center;
  max-width: calc(100% - 64px);
  line-height: 1.75;
  margin-top: 12px;
  color: #555;
}

.name {
  margin-top: 32px;
  font-size: 2rem;
  text-align: center;
  font-weight: bold;
  color: #707070;
}

.postit {
  display: block;
  margin-bottom: 32px;
  animation: headingPostitAnimation 1s ease forwards;
}

.titlePostit {
  animation: titlePostitAnimation 1s ease forwards;
}

.concept {
  text-align: center;
  line-height: 1.5;
  font-size: 2rem;
  color: #555555;
  font-weight: bold;
  max-width: 90%;
}

.galleryConcept {
  text-align: center;
  line-height: 1.5;
  font-size: 1.5rem;
  color: #555555;
  font-weight: bold;
  max-width: 90%;
}

.conceptDescription {
  text-align: center;
  max-width: 90%;
  margin-top: 32px;
  line-height: 2;
  color: #555;
}

.conceptDescription a {
  color: #555;
  font-weight: bold;
  text-decoration: none;
}

.galleryImg {
  margin: 64px 0 32px 0;
  width: 320px;
  height: auto;
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16);
}

.link {
  margin-bottom: 32px;
}

.appStoreButton {
  width: 210px;
  height: auto;
  overflow: hidden;
  margin-bottom: 12px;
}

.appStoreButton img {
  width: 100%;
  height: auto;
}

.appleAppStore {
  width: 180px;
  margin-bottom: 32px;
}

.smallCaption {
  font-size: 0.8rem;
  margin-top: 0;
}

.techs {
  margin-top: 64px;
  width: 75%;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  grid-gap: 32px;
  animation: imageAnimation 1s ease forwards;
}

/* Animation */
@keyframes titlePostitAnimation {
  from {
    transform: translateY(-147px);
  }
  to {
    transform: translateY(0);
  }
}

@keyframes headingPostitAnimation {
  from {
    opacity: 0;
    transform: translateY(-64px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes imageAnimation {
  from {
    opacity: 0;
    transform: translateY(-32px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (min-width: 800px) {
  .content {
    padding-bottom: 64px;
  }
  .logo,
  .galleryImg {
    width: 480px;
  }
}
</style>
