// pages/works/trainlcd.vue
<template>
  <div>
    <section class="container">
      <article class="content">
        <app-postit class="postit" text="Dev/WebApp" />
        <img class="logo" src="~/assets/works/trainlcd.png" alt="TrainLCD" />
        <h2 class="name">TrainLCD</h2>
        <p class="bio">
          電車のLCDをスマホで
        </p>
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="TrainLCD" subtitle="コンセプト" />
      <article class="content">
        <h2 class="concept">
          暇だし電車のLCD作るか！ｗ
        </h2>
        <p class="conceptDescription">
          <a
            href="https://github.com/TinyKitten/StationAPI"
            target="_blank"
            rel="noopener noreferrer"
            >StationAPI</a
          >の応用例の一つです。<br />
          前から電車のLCDを再現したいと思っていて、
          <a
            href="https://github.com/TinyKitten/StationAPI"
            target="_blank"
            rel="noopener noreferrer"
            >StationAPI</a
          >の大型アップデートで色々取れるようにした影響で作ろうと思いました。
        </p>
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="TrainLCD" subtitle="デザイン" />
      <article class="content">
        <img
          class="galleryImg"
          src="~/assets/works/trainlcd.png"
          alt="TrainLCD"
        />
        <h2 class="galleryConcept">
          実物のLCDに近づくように
        </h2>
      </article>
    </section>
    <section class="container">
      <app-title-postit v-if="visible" title="TrainLCD" subtitle="リンク" />
      <article class="content">
        <a
          href="https://trainlcd.tinykitten.me"
          target="_blank"
          class="link"
          rel="noopener noreferrer"
        >
          <app-button text="使ってみる" />
        </a>
        <a
          href="https://github.com/TinyKitten/TrainLCD"
          target="_blank"
          class="link"
          rel="noopener noreferrer"
        >
          <app-button text="リポジトリ" />
        </a>
        <nuxt-link to="/" class="link">
          <app-button color="#555" text="戻る" />
        </nuxt-link>
      </article>
    </section>
  </div>
</template>

<script>
import AppTitlePostit from '~/components/AppTitlePostit.vue'
import AppPostit from '~/components/AppPostit.vue'
import AppButton from '~/components/AppButton.vue'
import { scrollMixin } from '~/mixins/scroll'

export default {
  components: {
    AppPostit,
    AppTitlePostit,
    AppButton
  },
  mixins: [scrollMixin],
  head: {
    title: 'TrainLCD',
    description: '電車のLCDをスマホで',
    meta: [
      { hid: 'og:site_name', property: 'og:site_name', content: 'TinyKitten' },
      { hid: 'og:type', property: 'og:type', content: 'article' },
      {
        hid: 'og:url',
        property: 'og:url',
        content: 'https://tinykitten.me/works/trainlcd/'
      },
      {
        hid: 'og:title',
        property: 'og:title',
        content: 'TrainLCD'
      },
      {
        hid: 'og:description',
        property: 'og:description',
        content: '電車のLCDをスマホで'
      },
      {
        hid: 'og:image',
        property: 'og:image',
        content: `https://tinykitten.me${require('~/assets/works/trainlcd.png')}`
      }
    ]
  }
}
</script>

<style scoped>
.container {
  position: relative;
  min-height: calc(100vh - 48px);
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}

.container:first-child {
  min-height: 100vh;
}

.content {
  width: 100%;
  min-height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  margin-top: 144px;
  padding-bottom: 32px;
}

.content:first-child {
  margin-top: 48px;
}

.container:nth-child(even) {
  background: #fafafa;
}

.logo {
  opacity: 0;
  width: 80%;
  height: auto;
  filter: drop-shadow(0 3px 6px rgba(0, 0, 0, 0.16));
  animation: imageAnimation 1s ease 0.25s forwards;
}

.bio {
  text-align: center;
  max-width: calc(100% - 64px);
  line-height: 1.75;
  margin-top: 12px;
  color: #555;
}

.name {
  margin-top: 32px;
  font-size: 2rem;
  text-align: center;
  font-weight: bold;
  color: #707070;
}

.postit {
  display: block;
  margin-bottom: 32px;
  animation: headingPostitAnimation 1s ease forwards;
}

.titlePostit {
  animation: titlePostitAnimation 1s ease forwards;
}

.concept {
  text-align: center;
  line-height: 1.5;
  font-size: 2rem;
  color: #555555;
  font-weight: bold;
  max-width: 90%;
}

.galleryConcept {
  text-align: center;
  line-height: 1.5;
  font-size: 1.5rem;
  color: #555555;
  font-weight: bold;
  max-width: 90%;
}

.conceptDescription {
  text-align: center;
  max-width: 90%;
  margin-top: 32px;
  line-height: 2;
  color: #555;
}

.conceptDescription a {
  color: #555;
  font-weight: bold;
  text-decoration: none;
}

.galleryImg {
  margin: 64px 0 32px 0;
  width: 80%;
  height: auto;
  filter: drop-shadow(0 3px 6px rgba(0, 0, 0, 0.16));
}

.link {
  margin-bottom: 32px;
}

/* Animation */
@keyframes titlePostitAnimation {
  from {
    transform: translateY(-147px);
  }
  to {
    transform: translateY(0);
  }
}

@keyframes headingPostitAnimation {
  from {
    opacity: 0;
    transform: translateY(-64px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes imageAnimation {
  from {
    opacity: 0;
    transform: translateY(-32px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (min-width: 800px) {
  .logo {
    width: 25%;
  }
  .galleryImg {
    width: 25%;
  }
  .content {
    padding-bottom: 64px;
  }
}
</style>

// components/screens/Works/TrainLCD.tsx
import Image from 'next/image';
import Link from 'next/link';
import { useRef, useState } from 'react';
import styled from 'styled-components';
import TrainLCDImage from '../../../assets/works/trainlcd.png';
import {
  headingPostitAnimation,
  imageAnimation,
} from '../../../constants/keyframets';
import ScreenVisibleProvider from '../../../providers/ScreenVisibleProvider';
import Button from '../../Button';
import Postit from '../../Postit';

const ContentContainer = styled.div`
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
  min-height: calc(100vh - 48px);
`;

const LogoContainer = styled.div`
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const StyledPostit = styled(Postit)`
  position: absolute;
  transform: rotate(5deg);
  left: auto;
  right: auto;
  bottom: -24px;
  z-index: 1;
  animation: ${headingPostitAnimation} 1s ease 0.25s forwards;
  opacity: 0;
`;

const ImageContainer = styled.div`
  width: 480px;
  max-width: 75%;
  height: auto;
  filter: drop-shadow(0 3px 6px rgba(0, 0, 0, 0.16));
  animation: ${imageAnimation} 1s ease forwards;
`;

const Description = styled.p`
  text-align: center;
  max-width: calc(100% - 64px);
  line-height: 1.75;
  margin-top: 48px;
  color: ${({ theme }) => theme.headingText};
  animation: ${imageAnimation} 1s ease forwards;
`;

const LearnMoreButton = styled(Button)`
  margin: 32px 0;
  animation: ${imageAnimation} 1s ease forwards;
`;

const WorksTrainLCD: React.FC = () => {
  const [visible, setVisible] = useState(false);
  const ref = useRef(null);

  return (
    <ScreenVisibleProvider contentRef={ref} onVisibleChange={setVisible}>
      <ContentContainer ref={ref}>
        {visible && (
          <LogoContainer>
            <StyledPostit>TrainLCD</StyledPostit>
            <ImageContainer>
              <Image src={TrainLCDImage} alt="TrainLCD" />
            </ImageContainer>
          </LogoContainer>
        )}

        {visible && (
          <Description>
            日本全国の鉄道路線で使える新感覚のナビゲーションアプリです。
          </Description>
        )}
        <Link href="/works/trainlcd" passHref>
          <div>
            {visible && <LearnMoreButton>さらに詳しく</LearnMoreButton>}
          </div>
        </Link>
      </ContentContainer>
    </ScreenVisibleProvider>
  );
};

export default WorksTrainLCD;
