// pages/index.vue
<template>
  <section class="container">
    <welcome-screen />
    <about-me-screen />
    <skills-screen />
    <works-screen />
    <share-screen />
  </section>
</template>

<script>
import WelcomeScreen from '~/components/WelcomeScreen.vue'
import AboutMeScreen from '~/components/AboutMeScreen.vue'
import SkillsScreen from '~/components/SkillsScreen.vue'
import WorksScreen from '~/components/WorksScreen.vue'
import ShareScreen from '~/components/ShareScreen.vue'

export default {
  components: {
    WelcomeScreen,
    AboutMeScreen,
    SkillsScreen,
    WorksScreen,
    ShareScreen
  }
}
</script>

<style scoped></style>

// pages/index.tsx
import { useRef } from 'react';
import WelcomeScreen from '../components/screens/Welcome';
import AboutScreen from '../components/screens/About';
import SkillsScreen from '../components/screens/Skills';
import WorksScreen from '../components/screens/Works';
import ShareScreen from '../components/screens/Share';
import styles from '../styles/pages/Index.module.css';
import ResumeScreen from '../components/screens/Resume';

export default function Home(): React.ReactElement {
  const aboutScreenRef = useRef<HTMLDivElement | null>(null);

  return (
    <div>
      <WelcomeScreen aboutScreenRef={aboutScreenRef} className={styles.child} />
      <AboutScreen ref={aboutScreenRef} className={styles.child} />
      <SkillsScreen className={styles.child} />
      <ResumeScreen className={styles.child} />
      <WorksScreen className={styles.child} />
      <ShareScreen className={styles.child} />
    </div>
  );
}
